version: '3.7'

services:
  database:
    container_name: pg-database
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ufes-pg-mikaella
      POSTGRES_DB: contact_tracing
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - postgres-network
      
  pgadmin:
    container_name: pg-database-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mikaellaferreira0@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ufes-pg-mikaella"
    ports:
      - "6543:80"
    depends_on:
      - database
    networks:
      - postgres-network
      
networks: 
  postgres-network:
    driver: bridge
