version: '3.7'

services:
  go-server:
    container_name: pg-go-server
    image: mikaellafs/pg-contacttracing
    env_file:
      - .env
    ports:
      - "50052:50052"
    volumes:
      - "../logs.txt:/app/logs.txt"
    depends_on:
      - cache
      - emqx1
    networks:
      - pg-network

  pgadmin:
    container_name: pg-database-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mikaellaferreira0@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "" # set password
    ports:
      - "6543:80"
  
  cache:
    container_name: pg-cache
    hostname: "pg.cache.redis"
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass "ufes-pg-mikaella" --appendonly yes
    volumes: 
      - ../cache:/data
    networks:
      - pg-network
  
  emqx1:
    container_name: pg-emqx-node1
    image: emqx/emqx:4.3.0
    hostname: "pg.node1.emqx"
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx"
      - "EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=" # set password
      - "EMQX_DASHBOARD__DEFAULT_USER__LOGIN=admin"
      - "EMQX_AUTH__USER__1__USERNAME=client"
      - "EMQX_AUTH__USER__1__PASSWORD=" # set password
      - "EMQX_LOADED_PLUGINS=emqx_dashboard"
    volumes:
      - ../tmp/emqx.lic:/opt/emqx/etc/emqx.lic
    ports:
      - 18083:18083 # dashboard
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 8085:8081
    networks:
      - pg-network
      
networks:
  pg-network:
    driver: bridge
