// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/contact_tracing.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Register             *Register `protobuf:"bytes,1,opt,name=register,proto3" json:"register,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9baba2bb3359f57, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetRegister() *Register {
	if m != nil {
		return m.Register
	}
	return nil
}

func (m *RegisterRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Register struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pk                   string   `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9baba2bb3359f57, []int{1}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

func (m *Register) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Register) GetPk() string {
	if m != nil {
		return m.Pk
	}
	return ""
}

func (m *Register) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ReportRequest struct {
	Report               *Report  `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9baba2bb3359f57, []int{2}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *ReportRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Report struct {
	UserId               string               `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DateStartSymptoms    *timestamp.Timestamp `protobuf:"bytes,2,opt,name=dateStartSymptoms,proto3" json:"dateStartSymptoms,omitempty"`
	DateDiagnostic       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=dateDiagnostic,proto3" json:"dateDiagnostic,omitempty"`
	DateReport           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=dateReport,proto3" json:"dateReport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9baba2bb3359f57, []int{3}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Report) GetDateStartSymptoms() *timestamp.Timestamp {
	if m != nil {
		return m.DateStartSymptoms
	}
	return nil
}

func (m *Report) GetDateDiagnostic() *timestamp.Timestamp {
	if m != nil {
		return m.DateDiagnostic
	}
	return nil
}

func (m *Report) GetDateReport() *timestamp.Timestamp {
	if m != nil {
		return m.DateReport
	}
	return nil
}

type RegisterResult struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerPk             string   `protobuf:"bytes,3,opt,name=serverPk,proto3" json:"serverPk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResult) Reset()         { *m = RegisterResult{} }
func (m *RegisterResult) String() string { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()    {}
func (*RegisterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9baba2bb3359f57, []int{4}
}

func (m *RegisterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResult.Unmarshal(m, b)
}
func (m *RegisterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResult.Marshal(b, m, deterministic)
}
func (m *RegisterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResult.Merge(m, src)
}
func (m *RegisterResult) XXX_Size() int {
	return xxx_messageInfo_RegisterResult.Size(m)
}
func (m *RegisterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResult proto.InternalMessageInfo

func (m *RegisterResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RegisterResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterResult) GetServerPk() string {
	if m != nil {
		return m.ServerPk
	}
	return ""
}

type ReportResult struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResult) Reset()         { *m = ReportResult{} }
func (m *ReportResult) String() string { return proto.CompactTextString(m) }
func (*ReportResult) ProtoMessage()    {}
func (*ReportResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9baba2bb3359f57, []int{5}
}

func (m *ReportResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResult.Unmarshal(m, b)
}
func (m *ReportResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResult.Marshal(b, m, deterministic)
}
func (m *ReportResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResult.Merge(m, src)
}
func (m *ReportResult) XXX_Size() int {
	return xxx_messageInfo_ReportResult.Size(m)
}
func (m *ReportResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResult proto.InternalMessageInfo

func (m *ReportResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReportResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*Register)(nil), "pb.Register")
	proto.RegisterType((*ReportRequest)(nil), "pb.ReportRequest")
	proto.RegisterType((*Report)(nil), "pb.Report")
	proto.RegisterType((*RegisterResult)(nil), "pb.RegisterResult")
	proto.RegisterType((*ReportResult)(nil), "pb.ReportResult")
}

func init() { proto.RegisterFile("proto/contact_tracing.proto", fileDescriptor_f9baba2bb3359f57) }

var fileDescriptor_f9baba2bb3359f57 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x41, 0xcb, 0xd3, 0x40,
	0x10, 0x35, 0xf1, 0x33, 0xb6, 0xf3, 0xd5, 0x68, 0x57, 0x90, 0x10, 0x05, 0x4b, 0x4e, 0x3d, 0x25,
	0x50, 0x11, 0xc4, 0x93, 0x54, 0x0f, 0xf6, 0x22, 0xba, 0xed, 0x45, 0x0f, 0xca, 0x26, 0xdd, 0x86,
	0xd0, 0x26, 0xbb, 0xee, 0x4e, 0x14, 0x8f, 0xfe, 0x5d, 0x7f, 0x85, 0x64, 0x37, 0xdb, 0xa6, 0x8a,
	0x16, 0xbe, 0xe3, 0xbc, 0x9d, 0x37, 0xfb, 0x66, 0xde, 0x83, 0xc7, 0x52, 0x09, 0x14, 0x59, 0x21,
	0x1a, 0x64, 0x05, 0x7e, 0x41, 0xc5, 0x8a, 0xaa, 0x29, 0x53, 0x83, 0x12, 0x5f, 0xe6, 0xf1, 0xd3,
	0x52, 0x88, 0xf2, 0xc0, 0x33, 0x83, 0xe4, 0xed, 0x2e, 0xc3, 0xaa, 0xe6, 0x1a, 0x59, 0x2d, 0x6d,
	0x53, 0xf2, 0x11, 0xee, 0x53, 0x5e, 0x56, 0x1a, 0xb9, 0xa2, 0xfc, 0x6b, 0xcb, 0x35, 0x92, 0x39,
	0x8c, 0x54, 0x0f, 0x45, 0xde, 0xcc, 0x9b, 0x5f, 0x2f, 0x26, 0xa9, 0xcc, 0xd3, 0x63, 0xdb, 0xf1,
	0x95, 0x3c, 0x81, 0xb1, 0xae, 0xca, 0x86, 0x61, 0xab, 0x78, 0xe4, 0xcf, 0xbc, 0xf9, 0x84, 0x9e,
	0x80, 0xe4, 0x1d, 0x8c, 0x1c, 0x87, 0x3c, 0x82, 0xa0, 0xd5, 0x5c, 0xad, 0xb6, 0x66, 0xe2, 0x98,
	0xf6, 0x15, 0x09, 0xc1, 0x97, 0x7b, 0x43, 0x1d, 0x53, 0x5f, 0xee, 0x49, 0x0c, 0x23, 0xc9, 0xb4,
	0xfe, 0x2e, 0xd4, 0x36, 0xba, 0x6d, 0xd0, 0x63, 0x9d, 0x7c, 0x80, 0x7b, 0x94, 0x4b, 0xa1, 0xd0,
	0x09, 0x4d, 0x20, 0x50, 0x06, 0xe8, 0x65, 0x82, 0x95, 0x69, 0x5a, 0xfa, 0x97, 0x0b, 0x12, 0x7f,
	0x79, 0x10, 0x58, 0xc2, 0x3f, 0x15, 0xbe, 0x85, 0xe9, 0x96, 0x21, 0x5f, 0x23, 0x53, 0xb8, 0xfe,
	0x51, 0x4b, 0x14, 0xb5, 0x36, 0x83, 0xae, 0x17, 0x71, 0x6a, 0xaf, 0x9b, 0xba, 0xeb, 0xa6, 0x1b,
	0x77, 0x5d, 0xfa, 0x37, 0x89, 0x2c, 0x21, 0xec, 0xc0, 0x37, 0x15, 0x2b, 0x1b, 0xa1, 0xb1, 0x2a,
	0xcc, 0x86, 0xff, 0x1f, 0xf3, 0x07, 0x83, 0xbc, 0x04, 0xe8, 0x10, 0xab, 0x39, 0xba, 0xba, 0xc8,
	0x1f, 0x74, 0x27, 0x9f, 0x21, 0x3c, 0x59, 0xad, 0xdb, 0x83, 0xd9, 0x59, 0x23, 0xc3, 0x56, 0x9b,
	0x9d, 0xef, 0xd0, 0xbe, 0x22, 0x11, 0xdc, 0xad, 0xb9, 0xd6, 0xac, 0xe4, 0xbd, 0x35, 0xae, 0xec,
	0xfc, 0xd1, 0x5c, 0x7d, 0xe3, 0xea, 0xfd, 0xde, 0xf9, 0xe3, 0xea, 0xe4, 0x15, 0x4c, 0x9c, 0x3f,
	0x37, 0x9b, 0xbe, 0xf8, 0xe9, 0x41, 0xf8, 0xda, 0x66, 0x79, 0x63, 0xa3, 0x4c, 0x9e, 0x0f, 0x42,
	0xf4, 0xf0, 0x2c, 0x86, 0x36, 0x04, 0x31, 0x39, 0x07, 0xbb, 0x9f, 0x93, 0x5b, 0xe4, 0x45, 0x17,
	0xeb, 0x4e, 0xcb, 0xaa, 0xd9, 0xf1, 0x02, 0x2b, 0xd1, 0x90, 0xe9, 0x20, 0x1d, 0x3d, 0xf7, 0xc1,
	0x10, 0xb2, 0xcc, 0x65, 0xf0, 0xe9, 0x2a, 0xcd, 0x64, 0x9e, 0x07, 0xe6, 0x9a, 0xcf, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x01, 0x3b, 0xaa, 0xf2, 0x63, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactTracingClient is the client API for ContactTracing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactTracingClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResult, error)
	ReportInfection(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResult, error)
}

type contactTracingClient struct {
	cc *grpc.ClientConn
}

func NewContactTracingClient(cc *grpc.ClientConn) ContactTracingClient {
	return &contactTracingClient{cc}
}

func (c *contactTracingClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResult, error) {
	out := new(RegisterResult)
	err := c.cc.Invoke(ctx, "/pb.ContactTracing/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactTracingClient) ReportInfection(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResult, error) {
	out := new(ReportResult)
	err := c.cc.Invoke(ctx, "/pb.ContactTracing/ReportInfection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactTracingServer is the server API for ContactTracing service.
type ContactTracingServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResult, error)
	ReportInfection(context.Context, *ReportRequest) (*ReportResult, error)
}

// UnimplementedContactTracingServer can be embedded to have forward compatible implementations.
type UnimplementedContactTracingServer struct {
}

func (*UnimplementedContactTracingServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedContactTracingServer) ReportInfection(ctx context.Context, req *ReportRequest) (*ReportResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportInfection not implemented")
}

func RegisterContactTracingServer(s *grpc.Server, srv ContactTracingServer) {
	s.RegisterService(&_ContactTracing_serviceDesc, srv)
}

func _ContactTracing_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactTracingServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ContactTracing/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactTracingServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactTracing_ReportInfection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactTracingServer).ReportInfection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ContactTracing/ReportInfection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactTracingServer).ReportInfection(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactTracing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ContactTracing",
	HandlerType: (*ContactTracingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ContactTracing_Register_Handler,
		},
		{
			MethodName: "ReportInfection",
			Handler:    _ContactTracing_ReportInfection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/contact_tracing.proto",
}
